apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: titanic
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: titanic
  minReplicas: 4
  maxReplicas: 6
